# Module manifest for module 'MrModuleTools'
# Generated by: Mike F. Robbins
# Generated on: 9/5/2018

@{
    RootModule = 'MrModuleTools'
    ModuleVersion = '1.3.0'
    GUID = '55ccc5b3-b3ab-4336-881d-e8282dd19913'
    Author = 'Mike F. Robbins'
    CompanyName = 'mikefrobbins.com'
    Copyright = '(c) Mike F. Robbins. All rights reserved.'
    Description = 'PowerShell Script Module Toolkit'
    PowerShellVersion = '7.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()

    FunctionsToExport = @(
                        'ConvertTo-MrCsv',
                        'ConvertTo-MrScriptBlock',
                        'Get-MrAst',
                        'Get-MrAstType',
                        'Get-MrFunctionsToExport',
                        'Get-MrModuleDependency',
                        'Get-MrPrivateCommand',
                        'Get-MrRequiredModule',
                        'Get-MrRequiredPSVersion',
                        'Get-MrToken',
                        'Get-MrVariableType',
                        'Test-MrFunctionsToExport'
    )

    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()

    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()

    PrivateData = @{
        PSData = @{
            Tags = @()
            LicenseUri = 'https://github.com/mikefrobbins/ModuleTools/blob/main/LICENSE'
            ProjectUri = 'https://github.com/mikefrobbins/ModuleTools'

            # IconUri = ''
            # ReleaseNotes = ''
            # Prerelease = ''
            # RequireLicenseAcceptance = False
            # ExternalModuleDependencies = ''

        }

    }

    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''

}
